# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../web_tool.bzl", "web_tool")

oncall("data_compression")

web_tool(
    name = "visualization-app",
    shared_srcs = ["../web_common:package_srcs"],
    workspace_package = "@openzl/visualization-app",
)
